using System;
using Newtonsoft.Json;

namespace Mapper.Models.Json {
    // Partial since it was not autogenerated.
    public partial class Address
    {
        public Address() {
            Geo = new Json.Geo();
        }
    }
}
