using System;
using Newtonsoft.Json;

namespace Mapper.Models.Json
{
    // Partial since it was not autogenerated.
    public partial class Users
    {
        public Users() {
            Address = new Json.Address();
            Company = new Json.Company();
        }
    }
}